/**
 * Script to generate per-team (BA, Dev, QA) schedule from JIRA CSV export.
 *
 * - Input:  outputs/jira-export.csv (generated by extract-jira-estimates.ts)
 * - Output: outputs/jira-team-schedule.csv (ready for Excel Gantt)
 *
 * For each ticket, this script:
 * - Derives a base estimate from Story Points / Original Estimate.
 * - Splits it into BA / Dev / QA effort shares.
 * - Calculates sequential start/end timestamps per team assuming working
 *   hours 09:00–13:00 and 14:00–18:00 on working days (Mon–Fri).
 *
 * Usage:
 *   npx ts-node generate-team-schedule-from-jira.ts
 */

import { readFileSync, writeFileSync } from 'fs';
// csv-parse does not ship full TypeScript typings in this project context.
// Suppress type checking for this import while still using the runtime module.
// @ts-ignore
import { parse } from 'csv-parse/sync';
import { defaultConfig } from './src/config/types';
import { validateAndProcessEstimate } from './src/processors/estimate-processor';

type CsvRow = Record<string, string>;

interface TeamSegmentRow {
  issueKey: string;
  summary: string;
  issueType: string;
  status: string;
  jiraTeam: string;
  role: 'BA' | 'Dev' | 'QA';
  executionTeam: string;
  estimateHours: number;
  /**
   * Ticket-level estimate in Story Points (same for all BA/Dev/QA segments of a ticket).
   */
  storyPoints?: number;
  latestSprint?: string;
  start: string; // Local datetime string "YYYY-MM-DD HH:mm"
  end: string;   // Local datetime string "YYYY-MM-DD HH:mm"
}

interface TicketEstimate {
  storyPoints?: number;
  baseHours: number;
}

interface TeamConfig {
  id: string;
  name: string;
  velocity?: number;
  velocityPeriod?: string;
  members?: string[];
  matchRules?: {
    jiraTeam?: string[];
    issueTypes?: string[];
    statuses?: string[];
    components?: string[];
    labels?: string[];
    summaryText?: string[];
  };
}

interface TeamsConfig {
  projectStartDate?: string;
  projectReschedulingDate?: string;
  sprintDurationDays?: number;
  /**
   * Optional list of issue types that should be included in schedule planning.
   * Example: ["Story"]
   */
  plannedIssueTypes?: string[];
  teams?: TeamConfig[];
}

interface VelocityContext {
  sprintDurationDays: number;
  defaultVelocity: number;
  baVelocity?: number;
  qaVelocity?: number;
  jiraTeamVelocities: Record<string, number>;
}

interface SprintInfo {
  endDate?: string;
  completeDate?: string;
}

/**
 * Loads team configuration (velocity, sprint duration, etc.) from team-config.json.
 */
function loadTeamsConfigFromFile(): TeamsConfig {
  try {
    const raw = readFileSync('team-config.json', 'utf-8');
    const parsed = JSON.parse(raw) as TeamsConfig;
    return parsed;
  } catch {
    // If config is missing or invalid, return empty object and rely on defaults
    return {};
  }
}

/**
 * Builds a velocity context map from the teams configuration.
 */
function buildVelocityContext(config: TeamsConfig): VelocityContext {
  const sprintDurationDays =
    typeof config.sprintDurationDays === 'number' && config.sprintDurationDays > 0
      ? config.sprintDurationDays
      : 10;

  const teams = config.teams || [];
  const velocities = teams
    .map((t) => t.velocity)
    .filter((v): v is number => typeof v === 'number' && v > 0);

  const defaultVelocity = velocities.length > 0 ? velocities[0] : 10;

  let baVelocity: number | undefined;
  let qaVelocity: number | undefined;
  const jiraTeamVelocities: Record<string, number> = {};

  for (const team of teams) {
    const velocity = team.velocity && team.velocity > 0 ? team.velocity : defaultVelocity;

    if (team.id === 'team-ba' || team.name === 'BA Team') {
      baVelocity = velocity;
    }

    if (team.id === 'team-qa' || team.name === 'QA Team') {
      qaVelocity = velocity;
    }

    const jiraTeams = team.matchRules?.jiraTeam;
    if (Array.isArray(jiraTeams)) {
      for (const jt of jiraTeams) {
        if (jt && !jiraTeamVelocities[jt]) {
          jiraTeamVelocities[jt] = velocity;
        }
      }
    }
  }

  return {
    sprintDurationDays,
    defaultVelocity,
    baVelocity,
    qaVelocity,
    jiraTeamVelocities,
  };
}

/**
 * Resolves the effective velocity for a specific segment (BA, Dev, QA) and Jira team.
 */
function getVelocityForSegment(
  role: 'BA' | 'Dev' | 'QA',
  jiraTeam: string,
  ctx: VelocityContext
): number {
  if (role === 'BA') {
    return ctx.baVelocity ?? ctx.defaultVelocity;
  }

  if (role === 'QA') {
    return ctx.qaVelocity ?? ctx.defaultVelocity;
  }

  // Dev
  if (jiraTeam && ctx.jiraTeamVelocities[jiraTeam]) {
    return ctx.jiraTeamVelocities[jiraTeam];
  }

  return ctx.defaultVelocity;
}

/**
 * Scales raw effort hours using team velocity and sprint duration so that:
 *   Duration (days) ≈ (Estimate (SP) / Velocity) * SprintDuration
 * assuming 1 Story Point ≈ 8 hours and effortHours ≈ SP * 8.
 *
 * In practice, this reduces/increases calendar duration per team based on velocity.
 */
function scaleHoursWithVelocity(
  effortHours: number,
  velocity: number,
  ctx: VelocityContext
): number {
  if (!isFinite(effortHours) || effortHours <= 0) {
    return 0;
  }

  const v = velocity > 0 ? velocity : ctx.defaultVelocity;
  const sprintDays = ctx.sprintDurationDays > 0 ? ctx.sprintDurationDays : 10;

  // Derived from: durationDays = (SP / v) * sprintDays; effortHours ≈ SP * 8; hoursPerDay ≈ 8
  // => durationHours ≈ effortHours * sprintDays / v
  return effortHours * (sprintDays / v);
}

// Effort split per ticket (must sum to 1.0)
const BA_SHARE = 0.25;
const QA_SHARE = 0.30;
const DEV_SHARE = 1 - BA_SHARE - QA_SHARE; // 0.45

// Assumed hours per Story Point when only Story Points are available
const HOURS_PER_STORY_POINT = 8;

// Input/Output paths
const INPUT_CSV_PATH = 'outputs/jira-export.csv';
const OUTPUT_CSV_PATH = 'outputs/jira-team-schedule.csv';
const SPRINTS_CSV_PATH = 'outputs/jira-export-sprints.csv';

/**
 * Simple helper to extract a field from a CSV row with alternative names.
 */
function extractField(
  row: CsvRow,
  primaryName: string,
  alternativeNames: string[] = []
): string | undefined {
  if (row[primaryName] !== undefined) {
    return row[primaryName];
  }

  for (const alt of alternativeNames) {
    if (row[alt] !== undefined) {
      return row[alt];
    }
  }

  return undefined;
}

/**
 * Loads sprint data from sprints CSV and builds a lookup map.
 * Returns a Map: sprintName -> SprintInfo
 */
function loadSprintMap(): Map<string, SprintInfo> {
  const sprintMap = new Map<string, SprintInfo>();

  try {
    const sprintsContent = readFileSync(SPRINTS_CSV_PATH, 'utf-8');
    const sprintRecords = parse(sprintsContent, {
      columns: true,
      skip_empty_lines: true,
      trim: true,
      relax_column_count: true,
    }) as CsvRow[];

    for (const sprintRow of sprintRecords) {
      const sprintName = sprintRow['Name'] || '';
      const endDate = sprintRow['End Date'] || undefined;
      const completeDate = sprintRow['Complete Date'] || undefined;

      if (sprintName) {
        sprintMap.set(sprintName, {
          endDate,
          completeDate,
        });
      }
    }

    console.log(`Loaded ${sprintMap.size} sprints from ${SPRINTS_CSV_PATH}`);
  } catch (error) {
    console.warn(
      `Warning: Could not load sprints CSV from ${SPRINTS_CSV_PATH}. Sprint-based ordering will be limited.`
    );
  }

  return sprintMap;
}

/**
 * Extracts the latest sprint name from a comma-separated sprint field.
 * Returns the last sprint name in the list (most recent), or undefined if empty.
 */
function getLatestSprint(sprintField: string | undefined): string | undefined {
  if (!sprintField || sprintField.trim() === '') {
    return undefined;
  }

  const sprints = sprintField.split(',').map((s) => s.trim()).filter((s) => s.length > 0);
  return sprints.length > 0 ? sprints[sprints.length - 1] : undefined;
}

/**
 * Determines if a ticket is completed.
 * Returns true if ticket's Status Category is "DONE".
 */
function isCompletedTicket(row: CsvRow): boolean {
  const statusCategory = extractField(row, 'Status Category', ['statusCategory', 'Status Category']);

  // Check if Status Category is "DONE" (case-insensitive)
  if (statusCategory && statusCategory.toUpperCase() === 'DONE') {
    return true;
  }

  return false;
}

/**
 * Gets the sprint end date for a sprint name from the sprint map.
 * Returns the endDate string or undefined if sprint not found.
 */
function getSprintEndDate(
  sprintName: string | undefined,
  sprintMap: Map<string, SprintInfo>
): string | undefined {
  if (!sprintName) {
    return undefined;
  }

  const sprintInfo = sprintMap.get(sprintName);
  return sprintInfo?.endDate;
}

/**
 * Returns true if the given date is a weekend (Saturday or Sunday).
 */
function isWeekend(date: Date): boolean {
  const day = date.getDay(); // 0 = Sunday, 6 = Saturday
  return day === 0 || day === 6;
}

/**
 * Moves the date forward to the start (09:00) of the next working day (Mon–Fri).
 */
function startOfNextWorkingDay(date: Date): Date {
  const d = new Date(date.getTime());
  // Move to next day, 09:00
  d.setDate(d.getDate() + 1);
  d.setHours(9, 0, 0, 0);

  // Skip weekends
  while (isWeekend(d)) {
    d.setDate(d.getDate() + 1);
    d.setHours(9, 0, 0, 0);
  }

  return d;
}

/**
 * Ensures the given Date is aligned to working time:
 * - If weekend → move to next working day 09:00.
 * - If before 09:00 → set to 09:00.
 * - If between 13:00–14:00 → set to 14:00.
 * - If after 18:00 → move to next working day 09:00.
 * - If within [09:00–13:00) or [14:00–18:00) → unchanged.
 */
function normalizeToWorkingTime(input: Date): Date {
  let d = new Date(input.getTime());

  // Skip weekends
  if (isWeekend(d)) {
    return startOfNextWorkingDay(d);
  }

  const hours = d.getHours() + d.getMinutes() / 60;

  if (hours < 9) {
    d.setHours(9, 0, 0, 0);
  } else if (hours >= 13 && hours < 14) {
    d.setHours(14, 0, 0, 0);
  } else if (hours >= 18) {
    d = startOfNextWorkingDay(d);
  }

  // If now on weekend after adjustment, move again
  if (isWeekend(d)) {
    return startOfNextWorkingDay(d);
  }

  return d;
}

/**
 * Adds working hours to a start Date, respecting:
 * - Working days: Monday–Friday.
 * - Working hours: 09:00–13:00 and 14:00–18:00.
 * - Lunch break: 13:00–14:00 (non-working).
 *
 * @param start - Start Date (will be normalized to working time)
 * @param hours - Working hours to add (can be fractional)
 * @returns End Date aligned to working time
 */
function addWorkingHours(start: Date, hours: number): Date {
  if (hours <= 0) {
    return normalizeToWorkingTime(start);
  }

  let remaining = hours;
  let current = normalizeToWorkingTime(start);

  while (remaining > 1e-6) {
    current = normalizeToWorkingTime(current);

    // Ensure we are on a working day
    if (isWeekend(current)) {
      current = startOfNextWorkingDay(current);
      continue;
    }

    const currentHours = current.getHours() + current.getMinutes() / 60;
    let blockEndHour: number | null = null;

    if (currentHours >= 9 && currentHours < 13) {
      blockEndHour = 13;
    } else if (currentHours >= 14 && currentHours < 18) {
      blockEndHour = 18;
    } else {
      // Outside working blocks, normalize again
      current = normalizeToWorkingTime(current);
      continue;
    }

    const availableInBlock = blockEndHour - currentHours;
    const used = Math.min(availableInBlock, remaining);

    // Advance time by 'used' hours
    current = new Date(current.getTime() + used * 60 * 60 * 1000);
    remaining -= used;

    if (remaining <= 1e-6) {
      break;
    }

    // If block is exhausted but hours remain, move to next working segment
    current = normalizeToWorkingTime(current);
  }

  return normalizeToWorkingTime(current);
}

/**
 * Formats Date into "YYYY-MM-DD HH:mm" for Excel-friendly import.
 */
function formatDateTimeLocal(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

/**
 * Loads project start / rescheduling date from team configuration.
 * Falls back to "2025-01-01" if configuration is missing.
 */
function loadProjectStartDateTime(config: TeamsConfig): Date {
  let projectStartDate = '2025-01-01';

  if (config) {
    projectStartDate =
      config.projectReschedulingDate ||
      config.projectStartDate ||
      projectStartDate;
  }

  let start = new Date(`${projectStartDate}T09:00:00`);

  // If the chosen date is a weekend, move to next working day
  if (isWeekend(start)) {
    start = startOfNextWorkingDay(start);
  } else {
    start.setHours(9, 0, 0, 0);
  }

  return start;
}

/**
 * Finds the matching team for a ticket based on Team, Label, Summary text, and Component.
 * Priority order:
 * 1. Team field (jiraTeam) - if present and matches
 * 2. Labels - if Team is empty or doesn't match
 * 3. Summary text - if Labels don't match or are empty
 * 4. Component - only if none of the above matched
 *
 * Returns the team's jiraTeam value (first match from jiraTeam array) or empty string if no match.
 * Stops checking once the first match is found.
 */
function findMatchingTeam(
  row: CsvRow,
  teamsConfig: TeamsConfig
): string {
  const jiraTeam = extractField(row, 'Team', ['team', 'Jira Team']) || '';
  const component = extractField(row, 'Component', ['component']) || '';
  const labels = extractField(row, 'Labels', ['labels']) || '';
  const summary = extractField(row, 'Summary', ['Title', 'title']) || '';

  const teams = teamsConfig.teams || [];

  // First, try to match by Team field (jiraTeam) - if present
  if (jiraTeam && jiraTeam.trim() !== '') {
    for (const team of teams) {
      const teamJiraTeams = team.matchRules?.jiraTeam;
      if (Array.isArray(teamJiraTeams) && teamJiraTeams.includes(jiraTeam)) {
        return jiraTeam;
      }
    }
  }

  // If Team is empty or doesn't match, try Labels
  if (labels && labels.trim() !== '') {
    for (const team of teams) {
      const teamLabels = team.matchRules?.labels;
      if (Array.isArray(teamLabels) && teamLabels.length > 0) {
        // Labels field may contain comma-separated values
        const labelList = labels.split(',').map(l => l.trim());
        const matches = labelList.some(l => 
          teamLabels.some(tl => 
            l.toLowerCase() === tl.toLowerCase() || 
            l.toLowerCase().includes(tl.toLowerCase()) ||
            tl.toLowerCase().includes(l.toLowerCase())
          )
        );
        if (matches) {
          const teamJiraTeams = team.matchRules?.jiraTeam;
          if (Array.isArray(teamJiraTeams) && teamJiraTeams.length > 0) {
            return teamJiraTeams[0];
          }
          return team.name;
        }
      }
    }
  }

  // If Labels don't match or are empty, try Summary text
  if (summary && summary.trim() !== '') {
    const summaryLower = summary.toLowerCase();
    for (const team of teams) {
      const teamSummaryTexts = team.matchRules?.summaryText;
      if (Array.isArray(teamSummaryTexts) && teamSummaryTexts.length > 0) {
        const matches = teamSummaryTexts.some(st => 
          summaryLower.includes(st.toLowerCase())
        );
        if (matches) {
          const teamJiraTeams = team.matchRules?.jiraTeam;
          if (Array.isArray(teamJiraTeams) && teamJiraTeams.length > 0) {
            return teamJiraTeams[0];
          }
          return team.name;
        }
      }
    }
  }

  // If SummaryText doesn't match, try Component (only if none of the above matched)
  if (component && component.trim() !== '') {
    for (const team of teams) {
      const teamComponents = team.matchRules?.components;
      if (Array.isArray(teamComponents) && teamComponents.length > 0) {
        // Component field may contain comma-separated values
        const componentList = component.split(',').map(c => c.trim());
        const matches = componentList.some(c => 
          teamComponents.some(tc => 
            c.toLowerCase() === tc.toLowerCase() || 
            c.toLowerCase().includes(tc.toLowerCase()) ||
            tc.toLowerCase().includes(c.toLowerCase())
          )
        );
        if (matches) {
          // Return the first jiraTeam from this team's config, or team name as fallback
          const teamJiraTeams = team.matchRules?.jiraTeam;
          if (Array.isArray(teamJiraTeams) && teamJiraTeams.length > 0) {
            return teamJiraTeams[0];
          }
          return team.name;
        }
      }
    }
  }

  // No match found, return original jiraTeam or empty
  return jiraTeam;
}

/**
 * Interface for fake sprint information.
 */
interface FakeSprint {
  name: string;
  startDate: string;
  endDate: string;
  assignedTickets: CsvRow[];
}

/**
 * Generates fake sprints for tickets without sprints and assigns tickets to them.
 * Returns array of fake sprints and updates the records with assigned sprint names.
 */
function generateFakeSprints(
  records: CsvRow[],
  sprintMap: Map<string, SprintInfo>,
  teamsConfig: TeamsConfig
): FakeSprint[] {
  // Find latest sprint end date
  let latestEndDate: Date | null = null;
  let latestSprintNumber = 0;

  sprintMap.forEach((sprintInfo, sprintName) => {
    if (sprintInfo.endDate) {
      const endDate = new Date(sprintInfo.endDate);
      if (!latestEndDate || endDate > latestEndDate) {
        latestEndDate = endDate;
      }
    }
    
    // Extract sprint number from name (e.g., "PSME Sp 10" -> 10)
    const match = sprintName.match(/\bSp\s+(\d+)\b/i);
    if (match && match[1]) {
      const sprintNum = parseInt(match[1], 10);
      if (sprintNum > latestSprintNumber) {
        latestSprintNumber = sprintNum;
      }
    }
  });

  // If no sprints found, start from project rescheduling date or start date
  if (!latestEndDate) {
    const projectStart = teamsConfig.projectReschedulingDate || teamsConfig.projectStartDate || '2025-12-22';
    latestEndDate = new Date(projectStart);
    latestEndDate.setHours(9, 0, 0, 0);
  }

  // Find all tickets without sprints
  const ticketsWithoutSprints: CsvRow[] = [];
  for (const row of records) {
    const sprintField = extractField(row, 'Sprint', ['sprint']);
    const latestSprint = getLatestSprint(sprintField);
    if (!latestSprint) {
      ticketsWithoutSprints.push(row);
    }
  }

  if (ticketsWithoutSprints.length === 0) {
    console.log('No tickets without sprints found. Skipping fake sprint generation.');
    return [];
  }

  console.log(`Found ${ticketsWithoutSprints.length} tickets without sprints. Generating fake sprints...`);

  // Group tickets by team and calculate total story points per team
  const teamTickets = new Map<string, Array<{ row: CsvRow; storyPoints: number }>>();
  const velocityContext = buildVelocityContext(teamsConfig);
  const sprintDurationDays = velocityContext.sprintDurationDays;

  for (const row of ticketsWithoutSprints) {
    const jiraTeam = findMatchingTeam(row, teamsConfig) || 'Unknown';
    const estimate = getTicketEstimate(row, 0);
    const storyPoints = estimate.storyPoints || 0;

    if (!teamTickets.has(jiraTeam)) {
      teamTickets.set(jiraTeam, []);
    }
    teamTickets.get(jiraTeam)!.push({ row, storyPoints });
  }

  // Generate fake sprints for each team
  const fakeSprints: FakeSprint[] = [];
  let currentSprintNumber = latestSprintNumber + 1;
  let currentStartDate = new Date(latestEndDate.getTime());
  
  // Move to next working day
  currentStartDate.setDate(currentStartDate.getDate() + 1);
  while (isWeekend(currentStartDate)) {
    currentStartDate.setDate(currentStartDate.getDate() + 1);
  }
  currentStartDate.setHours(9, 0, 0, 0);

  // Track the latest sprint end date across all teams to ensure sequential sprints
  let globalLatestEndDate = new Date(currentStartDate.getTime());

  teamTickets.forEach((tickets, jiraTeam) => {
    const teamVelocity = velocityContext.jiraTeamVelocities[jiraTeam] || velocityContext.defaultVelocity;
    const totalStoryPoints = tickets.reduce((sum, t) => sum + t.storyPoints, 0);
    const sprintsNeeded = Math.ceil(totalStoryPoints / teamVelocity);

    console.log(`Team ${jiraTeam}: ${totalStoryPoints} story points, ${teamVelocity} velocity → ${sprintsNeeded} sprints needed`);

    let remainingTickets = [...tickets];
    let currentCapacity = 0;
    let currentSprintTickets: CsvRow[] = [];

    for (let sprintIdx = 0; sprintIdx < sprintsNeeded || remainingTickets.length > 0; sprintIdx++) {
      // Calculate sprint dates - start from global latest end date
      const sprintStart = new Date(globalLatestEndDate.getTime());
      sprintStart.setDate(sprintStart.getDate() + 1);
      while (isWeekend(sprintStart)) {
        sprintStart.setDate(sprintStart.getDate() + 1);
      }
      sprintStart.setHours(9, 0, 0, 0);
      
      const sprintEnd = new Date(sprintStart);
      
      // Add sprint duration (working days)
      let workingDaysAdded = 0;
      while (workingDaysAdded < sprintDurationDays) {
        sprintEnd.setDate(sprintEnd.getDate() + 1);
        if (!isWeekend(sprintEnd)) {
          workingDaysAdded++;
        }
      }
      sprintEnd.setHours(18, 0, 0, 0);

      // Assign tickets to this sprint
      while (remainingTickets.length > 0 && currentCapacity < teamVelocity) {
        const ticket = remainingTickets[0];
        const ticketSP = ticket.storyPoints;
        
        if (currentCapacity + ticketSP <= teamVelocity || currentSprintTickets.length === 0) {
          // Add ticket to current sprint
          currentSprintTickets.push(ticket.row);
          currentCapacity += ticketSP;
          remainingTickets.shift();
        } else {
          // Ticket doesn't fit, start new sprint
          break;
        }
      }

      if (currentSprintTickets.length > 0) {
        const sprintName = `PSME Sp ${currentSprintNumber} (${formatSprintDate(sprintStart)}-${formatSprintDate(sprintEnd)})`;
        
        // Assign sprint to tickets
        for (const ticketRow of currentSprintTickets) {
          // Update the Sprint field in the row
          const existingSprint = extractField(ticketRow, 'Sprint', ['sprint']) || '';
          ticketRow['Sprint'] = existingSprint ? `${existingSprint}, ${sprintName}` : sprintName;
        }

        fakeSprints.push({
          name: sprintName,
          startDate: sprintStart.toISOString(),
          endDate: sprintEnd.toISOString(),
          assignedTickets: currentSprintTickets,
        });

        console.log(`  Created ${sprintName}: ${currentSprintTickets.length} tickets, ${currentCapacity} story points`);
      }

      // Prepare for next sprint
      currentSprintNumber++;
      
      // Update global latest end date for next sprint
      globalLatestEndDate = new Date(sprintEnd.getTime());
      
      currentCapacity = 0;
      currentSprintTickets = [];
    }
  });

  console.log(`Generated ${fakeSprints.length} fake sprints for tickets without sprints.`);
  return fakeSprints;
}

/**
 * Formats a date for sprint name (e.g., "12/22").
 */
function formatSprintDate(date: Date): string {
  const month = date.getMonth() + 1;
  const day = date.getDate();
  return `${month}/${day}`;
}

/**
 * Derives ticket-level estimate from a CSV row.
 *
 * Priority for schedule calculation:
 * - If Story Points are present → use them as-is.
 * - Else, if Original Estimate is present → use that numeric value as Story Points.
 * - Else, fall back to generic Estimate field via estimate processor.
 *
 * Both Story Points and Original Estimate are treated as "points" here and converted
 * to hours using HOURS_PER_STORY_POINT for schedule duration.
 */
function getTicketEstimate(row: CsvRow, rowNumber: number): TicketEstimate {
  let storyPoints: number | undefined;

  // 1) Try explicit Story Points column
  let spSource =
    extractField(row, 'Story Points', ['Story Points']) || '';

  // 2) If Story Points are empty, fall back to Original Estimate as SP source
  if (!spSource || spSource.trim() === '') {
    const originalEstimateRaw = extractField(row, 'Original Estimate', [
      'OriginalEstimate',
      'originalEstimate',
    ]);
    if (originalEstimateRaw && originalEstimateRaw.trim() !== '') {
      spSource = originalEstimateRaw;
    }
  }

  if (spSource && spSource.trim() !== '') {
    const sp = Number(spSource);
    if (!isNaN(sp) && sp > 0) {
      storyPoints = sp;
      return {
        storyPoints,
        baseHours: storyPoints * HOURS_PER_STORY_POINT,
      };
    }
  }

  // 3) Fallback: use generic Estimate field with existing processor
  const estimateValue = extractField(row, 'Estimate', [
    'Estimate',
    'estimate',
  ]);

  const processed = validateAndProcessEstimate(
    estimateValue,
    defaultConfig.defaultTeam,
    rowNumber
  );

  if (defaultConfig.defaultTeam.estimateType === 'story-points') {
    // When config is story-points, processed is SP; we can re-use it as storyPoints.
    storyPoints = processed;
    return {
      storyPoints,
      baseHours: processed * HOURS_PER_STORY_POINT,
    };
  }

  // Days-hours mode: processed is already hours, but we don't know Story Points
  return {
    storyPoints,
    baseHours: processed,
  };
}

/**
 * Main execution function.
 */
async function main() {
  // Load input CSV
  const csvContent = readFileSync(INPUT_CSV_PATH, 'utf-8');
  const records = parse(csvContent, {
    columns: true,
    skip_empty_lines: true,
    trim: true,
    relax_column_count: true,
  }) as CsvRow[];

  if (records.length === 0) {
    console.log(`No records found in ${INPUT_CSV_PATH}`);
    return;
  }

  // Load sprint map for lookup
  const sprintMap = loadSprintMap();

  // Load team configuration first (needed for fake sprint generation)
  const teamsConfig = loadTeamsConfigFromFile();

  // Filter out completed tickets (Status Category = "DONE")
  const nonCompletedRecords = records.filter((row) => !isCompletedTicket(row));

  // Generate fake sprints for tickets without sprints
  const fakeSprints = generateFakeSprints(nonCompletedRecords, sprintMap, teamsConfig);
  // Add fake sprints to sprint map
  for (const fakeSprint of fakeSprints) {
    sprintMap.set(fakeSprint.name, {
      endDate: fakeSprint.endDate,
      completeDate: fakeSprint.endDate, // Use end date as completion date for fake sprints
    });
  }

  console.log(
    `Filtered out ${records.length - nonCompletedRecords.length} completed tickets. Processing ${nonCompletedRecords.length} non-completed tickets.`
  );

  // Sort non-completed records: tickets with sprints first (by sprint End Date), then tickets without sprints
  const sortedRecords = [...nonCompletedRecords].sort((a, b) => {
    // Check for sprints
    const aSprintField = extractField(a, 'Sprint', ['sprint']);
    const bSprintField = extractField(b, 'Sprint', ['sprint']);
    const aLatestSprint = getLatestSprint(aSprintField);
    const bLatestSprint = getLatestSprint(bSprintField);

    // Tickets with sprints come before tickets without sprints
    if (aLatestSprint && !bLatestSprint) {
      return -1;
    }
    if (!aLatestSprint && bLatestSprint) {
      return 1;
    }

    // Both have sprints: sort by sprint End Date ascending
    if (aLatestSprint && bLatestSprint) {
      const aSprintEndDate = getSprintEndDate(aLatestSprint, sprintMap) || '';
      const bSprintEndDate = getSprintEndDate(bLatestSprint, sprintMap) || '';

      if (aSprintEndDate && bSprintEndDate) {
        return aSprintEndDate.localeCompare(bSprintEndDate);
      }
      if (aSprintEndDate) {
        return -1;
      }
      if (bSprintEndDate) {
        return 1;
      }
      // If sprint end dates not found, maintain order
      return 0;
    }

    // Both non-completed without sprints: maintain original order
    return 0;
  });

  // Load velocity context (teamsConfig already loaded above)
  const velocityContext = buildVelocityContext(teamsConfig);

  // Base start datetime for all teams
  const projectStart = loadProjectStartDateTime(teamsConfig);

  // Per-team cursors
  let baCursor = new Date(projectStart.getTime());
  let qaCursor = new Date(projectStart.getTime());
  const devCursors: Record<string, Date> = {};

  const rows: TeamSegmentRow[] = [];

  sortedRecords.forEach((row, index) => {
    const rowNumber = index + 2; // header is row 1

    const issueKey = extractField(row, 'Issue Key', ['ID', 'Id', 'id']) || '';
    const summary =
      extractField(row, 'Summary', ['Title', 'title']) || '';
    const issueType =
      extractField(row, 'Issue Type', ['IssueType', 'issueType']) || '';
    const status =
      extractField(row, 'Status', ['status']) || '';
    
    // Extract latest sprint for this ticket
    const sprintField = extractField(row, 'Sprint', ['sprint']);
    const latestSprint = getLatestSprint(sprintField);
    
    // Find matching team using Team, Component, Label, or Summary text
    const jiraTeam = findMatchingTeam(row, teamsConfig);

    if (!issueKey) {
      return;
    }

    // Filter by planned issue types, if configured
    if (
      teamsConfig.plannedIssueTypes &&
      teamsConfig.plannedIssueTypes.length > 0 &&
      issueType &&
      !teamsConfig.plannedIssueTypes.includes(issueType)
    ) {
      return;
    }

    const estimate = getTicketEstimate(row, rowNumber);
    const baseHours = estimate.baseHours;
    const storyPoints = estimate.storyPoints;

    if (!isFinite(baseHours) || baseHours <= 0) {
      return;
    }

    const baHoursRaw = baseHours * BA_SHARE;
    const qaHoursRaw = baseHours * QA_SHARE;
    let devHoursRaw = baseHours * DEV_SHARE;

    // Round to 2 decimals for output, fix any small negative due to rounding
    const baHours = Math.max(0, Number(baHoursRaw.toFixed(2)));
    const qaHours = Math.max(0, Number(qaHoursRaw.toFixed(2)));
    devHoursRaw = Math.max(0, devHoursRaw);
    const devHours = Math.max(
      0,
      Number(devHoursRaw.toFixed(2))
    );

    // BA segment
    const baStart = new Date(baCursor.getTime());
    const baVelocity = getVelocityForSegment('BA', jiraTeam, velocityContext);
    const baDurationHours = scaleHoursWithVelocity(
      baHours,
      baVelocity,
      velocityContext
    );
    const baEnd = addWorkingHours(baStart, baDurationHours);
    rows.push({
      issueKey,
      summary,
      issueType,
      status,
      jiraTeam,
      role: 'BA',
      executionTeam: 'BA Team',
      estimateHours: baHours,
      storyPoints,
      latestSprint,
      start: formatDateTimeLocal(baStart),
      end: formatDateTimeLocal(baEnd),
    });
    baCursor = baEnd;

    // Dev segment (per JIRA Team)
    const devTeamName = jiraTeam || 'Dev Team';
    if (!devCursors[devTeamName]) {
      devCursors[devTeamName] = new Date(projectStart.getTime());
    }
    const devStart = new Date(devCursors[devTeamName].getTime());
    const devVelocity = getVelocityForSegment('Dev', jiraTeam, velocityContext);
    const devDurationHours = scaleHoursWithVelocity(
      devHours,
      devVelocity,
      velocityContext
    );
    const devEnd = addWorkingHours(devStart, devDurationHours);
    rows.push({
      issueKey,
      summary,
      issueType,
      status,
      jiraTeam,
      role: 'Dev',
      executionTeam: devTeamName,
      estimateHours: devHours,
      storyPoints,
      latestSprint,
      start: formatDateTimeLocal(devStart),
      end: formatDateTimeLocal(devEnd),
    });
    devCursors[devTeamName] = devEnd;

    // QA segment
    const qaStart = new Date(qaCursor.getTime());
    const qaVelocity = getVelocityForSegment('QA', jiraTeam, velocityContext);
    const qaDurationHours = scaleHoursWithVelocity(
      qaHours,
      qaVelocity,
      velocityContext
    );
    const qaEnd = addWorkingHours(qaStart, qaDurationHours);
    rows.push({
      issueKey,
      summary,
      issueType,
      status,
      jiraTeam,
      role: 'QA',
      executionTeam: 'QA Team',
      estimateHours: qaHours,
      storyPoints,
      latestSprint,
      start: formatDateTimeLocal(qaStart),
      end: formatDateTimeLocal(qaEnd),
    });
    qaCursor = qaEnd;
  });

  // Generate CSV output
  const header = [
    'Issue Key',
    'Summary',
    'Issue Type',
    'Status',
    'Jira Team',
    'Role',
    'Execution Team',
    'Estimate Hours',
    'Story Points',
    'Latest Sprint',
    'Start',
    'End',
  ];

  const lines = rows.map((r) => {
    const escape = (value: string | number): string => {
      const str = String(value);
      if (str.includes(',') || str.includes('"') || str.includes('\n')) {
        return `"${str.replace(/"/g, '""')}"`;
      }
      return str;
    };

    return [
      escape(r.issueKey),
      escape(r.summary),
      escape(r.issueType),
      escape(r.status),
      escape(r.jiraTeam),
      escape(r.role),
      escape(r.executionTeam),
      escape(r.estimateHours),
      r.storyPoints !== undefined ? escape(r.storyPoints) : '',
      r.latestSprint !== undefined ? escape(r.latestSprint) : '',
      escape(r.start),
      escape(r.end),
    ].join(',');
  });

  const csvOutput = [header.join(','), ...lines].join('\n');
  writeFileSync(OUTPUT_CSV_PATH, csvOutput, 'utf-8');

  console.log(
    `Generated team schedule CSV with ${rows.length} rows at ${OUTPUT_CSV_PATH}`
  );
}

// Execute when run as a script
main().catch((error) => {
  console.error('Team schedule generation failed:', error);
  process.exit(1);
});



